export const categories: string[] = [
    // Handmade & Artisanal
  "Handmade Goods",
  "Artisan Products",
  "Handcrafted Jewelry",
  "Handmade Clothing",
  "Handmade Accessories",
  "Handmade Home Decor",
  "Handmade Furniture",
  "Handmade Candles",
  "Handmade Soaps & Cosmetics",
  "Handmade Pottery & Ceramics",
  "Handmade Leather Goods",
  "Handmade Woodwork",
  "Handmade Art & Crafts",
  "Handmade Gifts",
  "DIY & Crafts",
  
    // Food & Beverage
  "Restaurant",
  "Cafe",
  "Coffee Shop",
  "Bakery",
  "Fast Food",
  "Food Truck",
  "Catering",
  "Bar",
  "Pub",
  "Nightclub",

  // Retail & Shops
  "Grocery Store",
  "Convenience Store",
  "Clothing Store",
  "Fashion Boutique",
  "Shoe Store",
  "Jewelry Store",
  "Cosmetics Store",
  "Electronics Store",
  "Mobile Phone Shop",
  "Computer Store",
  "Furniture Store",
  "Home Decor Store",
  "Bookstore",
  "Toy Store",
  "Pet Shop",
  "Flower Shop",
  "Gift Shop",
  "Sporting Goods Store",

  // Services
  "Cleaning Service",
  "Laundry Service",
  "Repair Service",
  "Maintenance Service",
  "Delivery Service",
  "Courier Service",
  "Moving Service",
  "Security Service",
  "Event Planning",
  "Wedding Services",

  // Health & Wellness
  "Pharmacy",
  "Clinic",
  "Medical Practice",
  "Dental Clinic",
  "Optical Store",
  "Gym",
  "Fitness Center",
  "Yoga Studio",
  "Spa",
  "Massage Center",
  "Beauty Salon",
  "Hair Salon",
  "Barbershop",
  "Nail Salon",
  "Wellness Center",

  // Education & Training
  "School",
  "University",
  "Training Center",
  "Online Courses",
  "Tutoring",
  "Language School",
  "Music School",
  "Driving School",

  // Technology & Digital
  "Software Company",
  "Web Development",
  "Mobile App Development",
  "IT Services",
  "Cybersecurity",
  "Cloud Services",
  "SaaS",
  "Digital Marketing",
  "SEO Agency",
  "Content Creation",
  "Graphic Design",
  "UI/UX Design",
  "Game Development",

  // Media & Creative
  "Photography",
  "Videography",
  "Film Production",
  "Music Production",
  "Podcast",
  "Animation Studio",
  "Design Studio",
  "Advertising Agency",

  // E-Commerce & Online
  "E-commerce Store",
  "Online Marketplace",
  "Dropshipping",
  "Subscription Service",
  "Affiliate Business",

  // Finance & Legal
  "Accounting",
  "Bookkeeping",
  "Financial Services",
  "Investment Firm",
  "Insurance Agency",
  "Banking Services",
  "Legal Services",
  "Law Firm",
  "Tax Consulting",

  // Real Estate & Construction
  "Real Estate Agency",
  "Property Management",
  "Construction Company",
  "Architecture Firm",
  "Interior Design",
  "Engineering Services",
  "Home Renovation",

  // Automotive & Transportation
  "Car Dealership",
  "Car Rental",
  "Auto Repair",
  "Car Wash",
  "Motorcycle Shop",
  "Auto Parts Store",
  "Logistics Company",
  "Transportation Service",
  "Taxi Service",
  "Ride Sharing",

  // Travel & Hospitality
  "Hotel",
  "Motel",
  "Hostel",
  "Resort",
  "Guest House",
  "Travel Agency",
  "Tour Operator",
  "Vacation Rentals",

  // Manufacturing & Industrial
  "Manufacturing",
  "Factory",
  "Industrial Services",
  "Machinery Supplier",
  "Equipment Rental",
  "Packaging Company",
  "Wholesale Distributor",

  // Agriculture & Environment
  "Farm",
  "Agriculture Business",
  "Organic Products",
  "Livestock",
  "Fishing",
  "Forestry",
  "Recycling",
  "Renewable Energy",

  // Entertainment & Leisure
  "Entertainment Center",
  "Cinema",
  "Theater",
  "Amusement Park",
  "Arcade",
  "Gaming Lounge",
  "Sports Club",

  // Non-Profit & Organizations
  "Non-Profit Organization",
  "Charity",
  "Foundation",
  "NGO",
  "Community Organization",
  "Religious Organization",

  // Government & Public
  "Government Service",
  "Public Service",
  "Municipal Services",

  // Freelance & Personal
  "Freelancer",
  "Consultant",
  "Coach",
  "Personal Brand",
  "Influencer",
  "Creator",

  // Other
  "Startup",
  "Holding Company",
  "Import / Export",
  "Trading Company",
  "Other",
];
